Fix Ubuntu 24.04 - Noble
h0tw1r3/puppet-realmd pull request #8
Opened 2024-12-21 00:37 UTC by ccombs-trustamerica

2025-01-15 06:34 UTC, h0tw1r3 requested changes
thanks for the pr, can you update metadata.json?

2025-10-30 20:18 UTC, h0tw1r3 commented
> @h0tw1r3 the metadata.json is update, can we merge this :)

the metadata version change needs to be dropped 👎

2025-10-31 04:45 UTC, ashish1099 commented
@h0tw1r3 so new tag is planned for later ?

2025-11-01 01:00 UTC, h0tw1r3 commented
Yes.
Changing just the metadata release in a feature branch doesn't reflect all the other changes.

2026-06-03 15:32 UTC, h0tw1r3 commented
Added in #19

2026-06-03 15:32 UTC, closed without merging